### PR TITLE
Better arbitration and BPTM, and arbiter diagnostics

### PR DESCRIPTION
**Pull request by slacAWallace**
1. BPTM don't fail gracefully, and they don't provide any feedback that they failed.
2. BPTM don't have enough internal diagnostics to figure out what's going on.
3. 20 is too small for an arbiter pool. This either needs to be increased or arbiters need to stack.
4. The arbiter framework is susceptible to DoS from a bad client. The system needs to be more robust.
5. Arbiters are opaque and it is exceedingly difficult to know what their active requests are. This means no diagnostic which means no way of knowing or understanding what's going on.

### CODE REVIEW

**Comment by slacAWallace** [comment]
32bfdd8 @ZLLentz arbiters actually properly stack now. Tested!

**Comment by ZLLentz** [comment]
Awesome!

Now that arbiters stack... is there any consideration for splitting FFOs between arbiters and doing arbiter vetos?

For example, if I have devices on two sides of a stopper on the same PLC, can I create a "master" arbiter linked to the PMPS_PRE IO, a "first section" arbiter linked to FFO1, and a "second section" arbiter linked to FFO2? And then veto both the arbitration requests and the FFO2 when the stopper is in?

**Comment by slacAWallace** [comment]
Oh that's interesting....  this might actually be really simple to do...

The only issue I see is this sort of breaks preemptiveness, as we'll always be reacting to the stopper state change.

**Comment by ZLLentz** [comment]
Ah, you're right. We'd have to have control of the stopper or this doesn't work very well.

Is the correct way to do this to weave the stopper into the arbitration requests then?

**Comment by slacAWallace** [comment]
I would be OK with breaking preemptiveness in this case as my understanding is the stopper moves slowly enough..

Devices will never have a beam parameter set that represents the beam they're actually getting.. Definitely a shortcoming of PMPS. So their preemptive actions will timeout anyways :) and they'll just be applying fast faults masked by the stopper.

Unless they can ask the arbiter, hey, which stopper am I being vetoed by (sort of bloat?), and consider beam rate zero for themselves until the stopper is not in. So, doable, but messy for sure. This way they continue through the usual preemptive routine, and get their requests added to the arbiter system as normal, and don't timeout because they've determined for themselves that the beamrate is zero due to the upstream veto device.

**Pull request merged**
