### PR TITLE
DEV: Adding sDev name to address issue#82

### PR DESCRIPTION
**Pull request by ghalym**
Necessary function have been modified. This has been tested on a sim vac project. It didn't break older versions of the vacuum lib That doesn't include sDevname.
Need new updated Vacuum and Motions libs to include sDeviceName when calling BPTM.

image
CaptureTest

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]
Looks good to me! When this gets distributed we can update the PMPS UI appropriately and the pre-emptive requests tab will be a lot clearer!

**Comment by ZLLentz** [comment]
Docs build fails on `/home/travis/build/pcdshub/lcls-twincat-pmps/Solution Items` missing, so I suspect there is some trickery where one of the project files references this non-existent directory. Unrelated to this PR.

**Comment by ZLLentz** [comment]
I've added the corresponding update the pmps-ui as a PR. See https://github.com/pcdshub/pmps-ui/pull/43

**Comment by ghalym** [comment]
@slacAWallace any comments?

**Pull request merged**
